#!/bin/bash -eu

echo; echo == docker create command
docker help create

echo; echo == start a previously-created container

ID=$(docker create -it fedora bash)
docker start -i -a $ID

echo; echo == docker attach command
docker help attach

echo; echo == run the container as a daemon, then attach
container=$(docker run -d -it fedora bash)
docker attach $container

echo; echo == run a non-interactive command in the daemon
container=$(docker run -d -it fedora bash -c 'while true ; do date; sleep 1; done')
docker ps -l
docker stop $container

echo; echo = remove a container after it exits
docker run --rm fedora date
