#!/bin/bash -eu

echo; echo == docker search command
docker help search

echo; echo == search for fedora images
docker search fedora | head -n5

echo; echo == search for automated fedora images with at least 20 stars
docker search -s 20 --automated fedora
